language: node_js
node_js:
  - "node"
install:
  # We have a yarn.lock checked in, so travis will use `yarn`, but we
  # want to use `npm install` instead.
  - npm install
script:
  - npm run lint
  - npm test
  - npm run build
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
